version: '3'

services:
  web:
    build: .
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: seoulogue
      POSTGRES_PASSWORD: jasZeh-tunkix-qomhy3
volumes:
  postgres_data: